Repository Woorifisa-Finalproject-4team/Project-Guidebook, pull requests merged in 2023-08, with the labels that each got.

#8 init:프론트엔드 개발환경 구축
  frontend/calculator-front/.eslintrc.cjs
  frontend/calculator-front/.gitignore
  frontend/calculator-front/.vscode/extensions.json
  frontend/calculator-front/README.md
  frontend/calculator-front/index.html
  frontend/calculator-front/package-lock.json
  frontend/calculator-front/package.json
  frontend/calculator-front/public/favicon.ico
  frontend/calculator-front/src/App.vue
  frontend/calculator-front/src/assets/base.css
  frontend/calculator-front/src/assets/logo.svg
  frontend/calculator-front/src/assets/main.css
  frontend/calculator-front/src/main.js
  frontend/calculator-front/src/router/index.js
  frontend/calculator-front/src/views/AboutView.vue
  frontend/calculator-front/src/views/HomeView.vue
  frontend/calculator-front/vite.config.js
Labels: 프론트엔드

#9 Setting : 백엔드 프로젝트 세팅
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/example/backend/BackendApplication.java
  backend/src/main/java/com/example/backend/api/AddController.java
  backend/src/main/java/com/example/backend/model/Calculate.java
  backend/src/main/java/com/example/backend/repository/CalcualteRepository.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/example/backend/BackendApplicationTests.java
  backend/src/test/java/com/example/backend/api/AddControllerTest.java
Labels: chore, 백엔드

#13 Feat : Add Api 추가
  backend/src/main/java/com/example/backend/api/AddController.java
  backend/src/main/java/com/example/backend/model/Calculate.java
  backend/src/main/java/com/example/backend/repository/CalcualteRepository.java
Labels: 기능 추가, 백엔드

#15 feat : 프론트 더하기 화면 기능 구현
  frontend/calculator-front/src/App.vue
Labels: chore, 프론트엔드

#17 feat : 더하기 기능 프론트와 백 api
  backend/src/main/java/com/example/backend/api/AddController.java
  frontend/calculator-front/package-lock.json
  frontend/calculator-front/package.json
  frontend/calculator-front/src/App.vue
  frontend/calculator-front/src/main.js
  frontend/calculator-front/src/views/HomeView.vue
Labels: 기능 추가, 프론트엔드

#19 Feat : Add 테스트 코드 작성 완료
  backend/src/main/java/com/example/backend/api/AddController.java
  backend/src/main/java/com/example/backend/repository/CalcualteRepository.java
  backend/src/test/java/com/example/backend/api/AddControllerTest.java
Labels: 기능 추가, 백엔드
